name: Seventy74 - 01
favicon: null
layout_spectrum: 0.09664716059342027
typography_spectrum: 0.8408706299960613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.17298490297980607
  lightness: 0.9816518181469291
  saturation: 0.6231289263814688
  rhythmicContrast: 0.603369438322261
purpose: []
