name: Seventy74 - 01
favicon: null
layout_spectrum: 0.6982689592987299
typography_spectrum: 0.2948432704433799
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6291698554996401
  lightness: 0.826125861145556
  saturation: 0.6988032725639641
  rhythmicContrast: 0.2474924277048558
purpose: []
